name: Build - Linux

on:
  workflow_dispatch:
  release:
    types: [published]
  pull_request:
    types: [opened, synchronize, ready_for_review]
  push:
    branches:
      - "main" 

defaults:
  run:
    shell: bash

env:
  CONAN_DRIVECONTROLLER_REMOTE_URL: https://global-artifacts.se.com/artifactory/api/conan/drivecontroller-conan-prod-fed
  VERSION: ${{ github.event.release.tag_name || format('{0}{1}', 'temporary-build-', github.run_number) }}

jobs:
  build-linux:
    runs-on: [ubuntu-latest]
    timeout-minutes: 30
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build dll
        run: dotnet build -c Release  

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dll_version-${{env.VERSION}}
          path: ./bin/Release
          retention-days: 21
          if-no-files-found: error

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./bin/Release/Opc2Aml.dll
            ./bin/Release/Opc2Aml.deps.json
            ./bin/Release/Opc2Aml.pdb
            ./bin/Release/app.config.json
